### ISSUE TITLE
Official Languages - Armenia

### ISSUE THREAD

**Issue by yavrumian** [apilayer/restcountries#106]
_API_ mentions **Russian** as one of _official languages_ of **Armenia**, but Armenia has only _**one**_ _official language_ and that is **Armenian**. Please fix this as soon as possible.
**Sources:** 
http://www.president.am/en/constitution-2015/  (_article 20)_
https://en.wikipedia.org/wiki/Armenia#Languages

**Comment by yavrumian** [comment]
hey, any news?

**Comment by amatosg** [comment]
Hi @yavrumian, sadly this project looks stale. I've cloned this project and fixed this issue and is available at https://restcountries.com/v2/name/armenia. To show only certain fields it would be like https://restcountries.com/v2/name/armenia?fields=languages,name (note it uses colon instead of semicolon). The functionality is almost the same, there are a few things that need to change, this information is available at [here](https://gitlab.com/amatos/rest-countries).

**Comment by yavrumian** [comment]
Hey, thanks for the response, I think I can close this issue
