### ISSUE TITLE
Country names are not provided in Arabic 

### ISSUE THREAD

**Issue by walcom** [apilayer/restcountries#218]
Hi
I would like to use , but I need the Arabic country name, which is not provided! 
There is only in Farsi (Persian), but it is not accepted.
I can help providing translations, but how?

**Comment by amatosg** [comment]
Saldy this project doesn't get updated as often as we would like to. Because of that I cloned this project and it has the same functionality but the url is slightly different. You can see it [here](https://restcountries.com/). If you would like to add another language, you can edit this [file](https://gitlab.com/amatos/rest-countries/-/blob/master/countriesV2.json) and add your language to the "language" node.

**Comment by walcom** [comment]
I almost finished adding the Arabic names, but I dont have the permission to save my changes

**Comment by amatosg** [comment]
you have to create a pull request to the project (either mine or this one,
although this one might take a while, months maybe, to be merged)
