### ISSUE TITLE
Holy see in french is Saint-Siège

### ISSUE THREAD

**Issue by lepatachou** [apilayer/restcountries#240]
Hi

Thanks for this API !
Just a few fixes for the French translation : 
- Holy see is "Saint-Siège" (and the capital is "Vatican city")
- Kosovo = Kosovo in french

**Comment by amatosg** [comment]
I cloned this project [here](https://gitlab.com/amatos/rest-countries) and released [here](https://restcountries.com/) (as .com instead of .eu). I added the [French translation to Kosovo](https://restcountries.com/v2/name/kosovo) and corrected the [French translation for Saint Siège](https://restcountries.com/v2/name/vatican%20city).

**Comment by ePascalC** [comment]
Holy See updated to Vatican City and also the translation in French.
